[build-system]
requires = ["setuptools>=42", "wheel", "pybind11~=2.6.1", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "switchboard/_version.py"
